### ISSUE TITLE
Giving a project another name isn't reflected in the post-creation prompt

### ISSUE THREAD

**Issue by artyomchel** [graphcool/graphcool-cli#100]
Notice how even though the project file was called `twitter_staging.graphcool` in prompt #1 it still says `Open project.graphcool...`

![screen shot 2017-06-18 at 6 40 53 pm](https://user-images.githubusercontent.com/28609290/27262385-f5cf8f4a-5455-11e7-9beb-7789271346c7.png)

**Comment by marktani** [comment]
Is the file actually called `twitter_staging.graphcool`?

**Comment by artyomchel** [comment]
Yes.
