### ISSUE TITLE
change default region to us-west-2 for command graphcool init

### ISSUE THREAD

**Issue by sorenbs** [graphcool/graphcool-cli#105]
```sh
-r, --region <region>      AWS Region (options: us-west-2 (default), eu-west-1, ap-northeast-1)
```

The default region should be eu-west-1

**Comment by sorenbs** [comment]
As discussed with @marktani and @schickling, we should rather change the default region to be us-west-2 instead of changing the description.

**Comment by cjoudrey** [comment]
As far as I can tell ([init.ts](https://github.com/graphcool/graphcool-cli/blob/a4f7012d4acf45bc96edef0e6a9567f8c8355d87/src/commands/init.ts#L103), [api.ts](https://github.com/graphcool/graphcool-cli/blob/c0a9a8c3cf8688955f77398359dad2273dc42a48/src/api/api.ts#L56)) the default value of `region` is currently being set on the server side.

@sorenbs are you suggesting the CLI should pass `us-west-2` to the server when no region is specified? i.e. Default value would be set within the CLI code instead on the server side.

**Comment by sorenbs** [comment]
You are totally right @cjoudrey! We will change this on the server: https://github.com/graphcool/api-bugs/issues/135

Thanks a lot for your recent pull requests - that's awesome :-)

Translating the region enum to the `us-west-2` format in the CLI is a good idea. Would you be interested in creating a pr for this?

**Comment by cjoudrey** [comment]
> Translating the region enum to the `us-west-2` format in the CLI is a good idea. Would you be interested in creating a pr for this?

Yup, will do. I already have to do the reverse way too for #107. 😁
