### ISSUE TITLE
--region is ignored for init and init --copy

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-cli#115]
# problem

The `--region` parameter is ignored when used with `init` and `init --copy`. I can't say if this is a backend or CLI problem. `npm -g install graphcool; graphcool -v` says `1.0.3`.

# reproduction

Run `graphcool init --region 'us-west-2` or `graphcool init --copy <alias> --region 'us-west-2'`. The region of the project in the system API will be `EU_WEST_1`.

Using `graphcool init --region 'US_WEST_2'` results in the same behaviour.

**Comment by marktani** [comment]
The behaviour changed with the latest version `1.1.1`:

* Using `init --region` works as expected when the region is specified in capslock, for example `graphcool init --region 'US_WEST_2'` creates a new project in the `US_WEST_2` region.
* Using `init --copy <alias> --region` behaves unexpected, for example `graphcool init --copy <alias> --region 'US_WEST_2'` creates a project in the same region as the project `<alias>`, no matter what value is used for `--region`. As far as I understand, this is a limitation in the backend (cannot copy projects across regions), so `--copy` and `--region` should not be able to be used together.

* all the following commands result in the same error message:
  * graphcool init --region 'us-west-2'
  * graphcool init --region 'ap-northeast-1'
  * graphcool init --region 'eu-west-1'

  The error message is

![image](https://user-images.githubusercontent.com/1780597/27635938-7560fdba-5c09-11e7-9eb7-92ae59e1f2c5.png)

**Comment by kbrandwijk** [comment]
Related: no validation on region command line argument, causing direct passing of any value to API.
