### ISSUE TITLE
CLI uses wrong default region

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool-cli#122]
According to the `--help` command, the `us-west-2` is the default region, yet all projects I create using the CLI use `eu-west-1`.

https://github.com/graphcool/graphcool-cli/blob/32fdfb64d1b26d6121ff49a1d3696e68a9924e62/src/types.ts#L19

**Comment by marktani** [comment]
This is already tracked here: https://github.com/graphcool/api-bugs/issues/135
Related: #121

**Comment by kbrandwijk** [comment]
This is not a API bug, as the CLI doesn't depend on any default region (server-side), but always specifies one (`eu-west-1`) and documents another. Changing any defaults in the API wouldn't help...

**Comment by marktani** [comment]
Ah, good point! I'll add a comment to #121.
