### ISSUE TITLE
Error when copying project

### ISSUE THREAD

**Issue by skylinezum** [graphcool/graphcool-cli#123]
command seems to create a new project with correct settings, but cli returns an error: `Error: Unexpected token < in JSON at position 0`

**Comment by timsuchanek** [comment]
Thanks for reporting @skylinezum ! Can you provide the full command that you used to copy the project? This works for example in my tests:
```bash
$ graphcool init --copy cj55kzkurhrj10148lsdltiv6 --output test.graphcool
```

**Comment by skylinezum** [comment]
Hi @timsuchanek 
I reproduced it again. Here was the command and output in 1 line.
```bash
graphcool init test-dev -c wallo-dev-us-west-2 -a test1-dev -r us-west-2 -o test1.graphcool
✖  Error: Unexpected token < in JSON at position 0

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/
```

**Comment by marktani** [comment]
What's your `graphcool` version`? `graphcool -v`

**Comment by skylinezum** [comment]
it was at `v1.01`
but I upgraded it to `v1.2.1` and got the same error
```
graphcool init test-dev -c wallo-dev-us-west-2 -a test1-dev -o test1.graphcool
✖  Error: Unexpected token < in JSON at position 0
```

**Comment by timsuchanek** [comment]
We're removing the clone project feature right now. Short term you can use `graphcool init -c `, which will not copy (or clone) the project anymore, but create a new project just **based on the schema**. We're working on a more sophisticated import/export flow so in the future you also have the data copied over.
We're testing the new CLI in beta right now, if you're interested in testing it and not already doing so, you can contact @marktani for further information :)
