### ISSUE TITLE
Internal server error when running graphcool init for the first time

### ISSUE THREAD

**Issue by ColinDanforth** [graphcool/graphcool-cli#126]
when trying to authenticate my browser with graphcool I receive an error.

"whoops. looks like an internal server error. Please contact us from the console..."
Request ID: cj56t3p5yg6r60181994j5zv4

I'm unable to determine what is causing this issue. Any help would be greatly appreciated.

**Comment by marktani** [comment]
The command that initiates the auth flow is `graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews`.

**Comment by marktani** [comment]
Hey @ColinDanforth could you try again? 🙂

**Comment by ColinDanforth** [comment]
Perfect thank you. it seems to be loading as expected now.

**Comment by marktani** [comment]
Thanks! 🙂
