### ISSUE TITLE
graphcool init not authenticating

### ISSUE THREAD

**Issue by gr8w8** [graphcool/graphcool-cli#133]
You need to authenticate. Your browser will open shortly...×  Error: Whoops, something went wrong during authentication.
  graphcool Error: Whoops, something went wrong during authentication.
  graphcool
  graphcool     at Object.<anonymous> (C:\Users\25416\AppData\Roaming\npm\node_modules\graphcool\dist\src\commands\auth.js:25:19)
  graphcool     at Generator.throw (<anonymous>)
  graphcool     at rejected (C:\Users\25416\AppData\Roaming\npm\node_modules\graphcool\dist\src\commands\auth.js:5:65)
  graphcool     at process._tickDomainCallback (internal/process/next_tick.js:135:7) +0ms

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/

- You need to authenticate. Your browser will open shortly...raven@2.1.1 alert: failed to send exception to sentry: self signed certificate in certificate chain

**Comment by marktani** [comment]
Are you behind a firewall or proxy? Can you try again with the `DEBUG=graphcool` flag enabled?

**Comment by gr8w8** [comment]
Yes, I'm behind a firewall (at work)

**Comment by gr8w8** [comment]
Also, where do I enable DEBUG=graphcool? I tried export DEBUG=graphcool and that printed the information above.

**Comment by marktani** [comment]
What happens when you do the token-based authentication as described in the authentication tab in the project settings in the Console?

**Comment by gr8w8** [comment]
Where are the project settings?

**Comment by gr8w8** [comment]
So these are the steps I have take so far. 
npm install -g graphcool
graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews (from a tutorial I'm doing).

**Comment by gr8w8** [comment]
Never mind. Going to use a different option.
