### ISSUE TITLE
authentication fail

### ISSUE THREAD

**Issue by BranLiang** [graphcool/graphcool-cli#139]
Failed to init or pull existing project to local, location: Shanghai, China
Error message: You need to authenticate. Your browser will open shortly...✖  Error: Whoops, something went wrong during authentication.

**Comment by timsuchanek** [comment]
Thanks for raising this issue and sorry for the late answer!
We're doing a major rewrite of the CLI and try to make the errors more verbose so that this can even be debugged

**Comment by timsuchanek** [comment]
We increased the debugging for 1.3.13 beta, that should help us to get more information in the future. Feel free to reopen when this happens in the new CLI version.
