### ISSUE TITLE
Schema update to relation names fail via CLI (but work in console)

### ISSUE THREAD

**Issue by CameronK** [graphcool/graphcool-cli#142]
When using the CLI, any renamed relations seem to be ignored.

Here's my base schema:
```
type Device implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  user: User @relation(name: "UserDevices")
}
type User implements Node {
  createdAt: DateTime!
  devices: [Device!]! @relation(name: "UserDevices")
  id: ID! @isUnique
  updatedAt: DateTime!
}
```

Let's say I make a modification, like this:
```
type Device implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  user: User @relation(name: "DevicesOnUser")
}
type User implements Node {
  createdAt: DateTime!
  devices: [Device!]! @relation(name: "DevicesOnUser")
  id: ID! @isUnique
  updatedAt: DateTime!
}
```

[The docs for relation migration](https://www.graph.cool/docs/reference/migrations/relations-shiz6ov4ae/#renaming-an-existing-relation) seem to indicate that I need to modify the @relation directive on both fields. When I submit the above schema migration via `graphcool push`, I get this error: 

` ✔ Identical schema, no action required.`

However, copying and pasting into the Graphcool console works just fine (the relations are updated properly).

**Comment by timsuchanek** [comment]
Thanks for bringing this up @CameronK !
As this is backend related, I moved this issue to https://github.com/graphcool/graphcool/issues/534
