### ISSUE TITLE
Graphcool CLI crashes after installation

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/graphcool-cli#146]
Hi there, 

I just wanted to try the new graphcool CLI. I installed according to the install instructions: 

```
npm install -g graphcool
```

When invoking `graphcool`, I face the following error: 

```
/usr/local/lib/node_modules/graphcool/dist/src/index.js:34
const { version } = require('../../package.json');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

Since I'm using Node 4.8.1, I assume it might have to do something with this elderly node version. Which version have you tested the CLI for?

**Comment by ejoebstl** [comment]
Updating to node 6.11 fixed the issue. Please consider either transpiling or mentioning the requirement in your readme.

**Comment by timsuchanek** [comment]
Thanks for reporting @ejoebstl !
We will try to transpile it so older versions are supported

**Comment by timsuchanek** [comment]
We're now enforcing a higher node version in 1.3.13 and transpiling to es5.
Action item right now: Require a lower node version than 8.3, I'm creating a separate issue for that.
