### ISSUE TITLE
Readable filenames for permission queries

### ISSUE THREAD

**Issue by danmkent** [graphcool/graphcool-cli#164]
In graphcool-cli version `1.3.8`, pulling a project that have permission queries in it leads to the generation of files with names like `./query/cj70obsb104lv01983w3rnhqc.graphql`

It would be much nicer if these files had readable names, based on what they are applied to, such as `./query/Post_update.graphql`

When there is more than one permission query for a particular operation, they could be named sequentially ( `./query/Post_update_2.graphql` and so on)

**Comment by timsuchanek** [comment]
Thanks for bringing this up @danmkent ! As these filenames are generated by the backend, I moved this issue here: https://github.com/graphcool/graphcool/issues/535
