### ISSUE TITLE
Multiple permission queries for operation not pulled correctly

### ISSUE THREAD

**Issue by danmkent** [graphcool/graphcool-cli#165]
In graphcool-cli version `1.3.8`, pulling a project that has multiple permissions with permission queries for the same operation on the same type, causes things like this to happen:

```
- operation: Company.read
  authenticated: true
  query: ./query/cj77ronvy15hg0176jyncq7zh.graphql
- operation: Company.read
  authenticated: true
  query: ./query/.graphql
```

The first permission query is corrected stored in a file but the second one is not.

**Comment by kbrandwijk** [comment]
1.3.9: I'm seeing the same behavior for permission queries on system types.

**Comment by timsuchanek** [comment]
This happened due to the Console creating an empty name for the permission query.
The backend now sees this behavior and puts in a name like for normal queries.
