### ISSUE TITLE
Pull fails when graphcool.yml is not valid, even when using --force option

### ISSUE THREAD

**Issue by danmkent** [graphcool/graphcool-cli#166]
When using graphcool-cli version `1.3.8`, doing `graphcool pull` when the `graphcool.yml` file is invalid (in my case because function handlers had not been downloaded on previous pull) causes errors like this:

```
Errors while validating graphcool.yml:
  data.functions['add'].handler should NOT have less than 1 properties
  data.functions['add'].handler should NOT have less than 1 properties
  data.functions['add'].handler should match exactly one schema in oneOf
```
These errors occur even if the `--force` option is used:

```
Dans-MacBook-Pro-2:test3 programming$ graphcool pull --force
Errors while validating graphcool.yml:
  data.functions['add'].handler should NOT have less than 1 properties
  data.functions['add'].handler should NOT have less than 1 properties
  data.functions['add'].handler should match exactly one schema in oneOf
```
The only way to get a new pull to work is to delete the `graphcool.yml `file.

I would expect that the `--force` option would mean that the local file would not need to be valid

**Comment by timsuchanek** [comment]
We won't have the pull command anymore in the future, as projects will have to be ejected.
That means users of Graphcool will be responsible for having the code checked in to a versioning system like git themselves to prevent this error.
In the graphcool@1.3.13 there is still a rudimentary pull command, which is deprecated though.

If you still want to use the CLI based on an existing project, you can use the `graphcool init` command and "base" the new project of one of the existing ones
