### ISSUE TITLE
Error when trying to export data

### ISSUE THREAD

**Issue by aurnik** [graphcool/graphcool-cli#167]
I recently went to the CLI to try to export my data because it doesn't work from the console, however the CLI hasn't been much help either. After running `graphcool export` I just get

>  Error: invalid json response body at https://api.graph.cool/system reason: Unexpected token < in JSON at position 0

Has anyone had luck exporting from the CLI / know why this might be happening?

Here are the full logs:

> ⠋ Exporting your project data ...  graphcool Send request to https://api.graph.cool/system
>   graphcool Payload: 
>   graphcool {"query":"mutation ($projectId: String!){\n  exportData(input:{\n    projectId: $projectId,\n    clientMutationId: \"asd\"\n  }) {\n    url\n  }\n}","variables":{"projectId":"ProjectName"}} +0ms
> ✖  Error: invalid json response body at https://api.graph.cool/system reason: Unexpected token < in JSON at position 0
>   graphcool FetchError: invalid json response body at https://api.graph.cool/system reason: Unexpected token < in JSON at position 0
>   graphcool     at /usr/local/lib/node_modules/graphcool/node_modules/node-fetch/lib/body.js:48:31
>   graphcool     at process._tickDomainCallback (internal/process/next_tick.js:129:7) +31s

**Comment by timsuchanek** [comment]
Fixed in 1.3.13 (beta)
