### ISSUE TITLE
[1.3.9] no valid session after authentication, but project initialization still works

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-cli#178]
What happened:

* I ran `graphcool pull -p <id>`.
* I was prompted to authenticate in the Console and did that successfully
* I got the ` ✔ Authenticated user` confirmation in the terminal, followed by this error message:

> ✖  Error: No valid session: {"response":{"data":{"viewer":{"user":null}},"errors":[{"locations":[{"line":4,"column":11}],"path":["viewer","user"],"code":2001,"m
essage":"No valid session","requestId":"eu-west-1:system:cj7c8tmha02d001085n55feq3"}],"status":200},"request":{"query":"\n      {\n        viewer {\n          u
ser {\n            projects {\n              edges {\n                node {\n                  id\n                  name\n                  alias\n
       version\n                  region\n                }\n              }\n            }\n          }\n        }\n      }"}}
* the project was not pulled, so I ran `graphcool pull -p <id>` again. This time, it worked:

```
Checking out new project...
Written to graphcool.yml
Written to ./types.graphql
Written to ./code/slugifyName.js


Pulled project with id "<id>" and environment "dev"
```

It should have worked on the first time. Note that I did not do anything between the failed authentication and the working one.

**Comment by timsuchanek** [comment]
Fixed in 1.3.13
