### ISSUE TITLE
[1.3.6] `gc init` throws error when authenticating for the first time

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool-cli#180]
1. `gc init`
2. Browser opens for auth
3. ~\.graphcool is created
4. `gc init` command continues
5. Choose any project (blank or whatever)
6. Error
```Error: No valid session: {"response":{"data":{"addProject":null},"errors":[{"locations":[{"line":2,"column":9}],"path":["addProject"],"code":2001,"message":"No valid session","requestId":"eu-west-1:system:cj77zy0dp071f0189s7lb1e2e"}],"status":200}```

**Comment by marktani** [comment]
looks similar to #178

**Comment by kbrandwijk** [comment]
You're right, I couldn't find that one.
