### ISSUE TITLE
FR: Please kebab-case function filenames instead of using spaces

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool-cli#188]

**Comment by marktani** [comment]
Can you elaborate?

**Comment by kbrandwijk** [comment]
If I have a function called 'Do something', when I `gc pull` that project, it creates '**./code/Do something.js**'. I would rather have it create '**./code/do-something.js**', because I hate spaces (and uppercase, but that's a matter of taste), in my filenames.

**Comment by timsuchanek** [comment]
Thanks for bringing this up @kbrandwijk , as this is backend related, I moved it to https://github.com/graphcool/graphcool/issues/538
