### ISSUE TITLE
[1.3.13] Deploy doesn't create PATs

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool-cli#222]
I can't find the previous issue for this, but `gc deploy` does not deploy rootTokens, and I have no way to get the rootTokens into my project file, so the workflow is broken here from both sides, and I can't work headless.

**Comment by timsuchanek** [comment]
Thanks for bringing this up!
Let's continue with this issue in https://github.com/graphcool/graphcool/issues/536 as it is backend related
