### ISSUE TITLE
[1.3.13] Type already exists in project error when deploying

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool-cli#237]
I don't know exactly how to reproduce this, but I deployed a module with Type 'X'.
Then, renamed in to 'Y'.
Then, renamed it back to 'X'.

When deploying, I now get the error:
```
Global
    × A model with the name 'X' already exists in your project
```
Might be a back-end issue though...

**Comment by timsuchanek** [comment]
This issue was moved to graphcool/graphcool#549
