### ISSUE TITLE
[1.3.14] logs is not a graphcool command

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-cli#243]
![image](https://user-images.githubusercontent.com/1780597/30385313-14e98ea4-98a7-11e7-88e7-5cac8c495b4d.png)

**Comment by kbrandwijk** [comment]
There's a general inconsistency in all of the help texts. This screenshot also says that 'logs' is a `graphcool logs` command, which it isn't. It's a graphcool command.

**Comment by timsuchanek** [comment]
As said in the `Flags` section, function is now a Flag which you can provide with `-f`:
```
graphcool logs -f github-authentication --tail
```

**Comment by marktani** [comment]
The error message is still wrong and confusing.

**Comment by timsuchanek** [comment]
That's correct, we have multiple issues open for that problem

**Comment by marktani** [comment]
Can you link them? I couldn't find them. Thanks! 🙂

**Comment by timsuchanek** [comment]
#204, #205, #238 It's all based on the same problem and it's the next thing I want to tackle in the CLI

**Comment by kbrandwijk** [comment]
I suddenly noticed 1.3.14. I'm sorry, my comments were based on 1.3.13, missed the new version...
