### ISSUE TITLE
Init selection should be deleted

### ISSUE THREAD

**Issue by sorenbs** [graphcool/graphcool-cli#72]
![image](https://cloud.githubusercontent.com/assets/281337/26028869/cc508ad2-3828-11e7-9fbc-7026b879b87f.png)

**Comment by schickling** [comment]
@sorenbs is this still a problem for you using the newest version?

**Comment by sorenbs** [comment]
No. We changed the flow. The `How do you want to continue?` section doesn't exist anymore
