### ISSUE TITLE
Would be nice if a `graphcool pull` (and push) included the functions and mutation callbacks

### ISSUE THREAD

**Issue by kimf** [graphcool/graphcool-cli#82]
Keep them all in with the code, and version controlled would be awesome..

PS.. This new functions and cli stuff looks amazing

**Comment by wallslide** [comment]
Also need permission queries to be included!

**Comment by CameronK** [comment]
I read in an email that the team is working on some new features that might be related to this. Looking forward to more soon!

**Comment by marktani** [comment]
This feature is now in a closed beta. I'll close this issue, please refer to [the feature request](https://github.com/graphcool/feature-requests/issues/213#issuecomment-326635009) to track our progress here.
