### ISSUE TITLE
Enums not supported for schema import

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-cli#83]
![image](https://cloud.githubusercontent.com/assets/1780597/26265056/b2a74628-3cdf-11e7-9c29-df226764d859.png)

**Comment by schickling** [comment]
Depends on https://github.com/graphcool/api-bugs/issues/62

**Comment by kbrandwijk** [comment]
Dependent issue seems to have been fixed. This also seems to be working in latest beta.

**Comment by marktani** [comment]
That's right. Thanks 🙌
