### ISSUE TITLE
Allow for Different File Extensions

### ISSUE THREAD

**Issue by picosam** [graphcool/graphcool-cli#84]
I currently use WebStorm which has a useful GraphQL plugin. It only recognizes files with proper extensions though: for instance, it insists that schema files must end with `.graphqls`. It would thus be cool if we can control file names and extensions as necessary.

**Comment by divyenduz** [comment]
On the same context, do we have any extensions for Atom / VSCode that to highlight `.graphcool` schema?

**Comment by timsuchanek** [comment]
@divyenduz We're working on a plugin that will be released in the coming weeks to have Atom/VSCcode support.
@picosam In the new CLI version, we're back to .graphql files. If you're not already in the beta program for the CLI, you can contact @marktani for further information

**Comment by eruby94** [comment]
@divyenduz @timsuchanek 
You can easily configure atom to recognize a graphcool file extension to have graphql syntax highlighting by editing your config.cson (likely found at `~/.atom/config.cson`)

Just make your config look like this:
```
core:
  customFileTypes:
    'source.graphql': [
      'graphcool'
    ]
```
