### ISSUE TITLE
Tutorial: Graphcool Init fails and stalls on browser open

### ISSUE THREAD

**Issue by eddiewang** [graphcool/graphcool-cli#85]
The tutorial error when we use `graphcool start freecom.graphql` fails and stalls.
Similarly `graphcool init freecom.graphql` fails as well.

The solution to this bug is to use `graphcool init --schema freecom.graphql`

For anyone having troubles - here's the fix 👍

**Comment by schickling** [comment]
Both `graphcool start freecom.graphql` and `graphcool init freecom.graphql` look like a older version of the CLI syntax. Would you mind sharing the links/resources where these snippets are coming from?

**Comment by marktani** [comment]
That would be the Freecom tutorial (I believe in the videos). This is related to #77.
