### ISSUE TITLE
Can't authenticate in terminal-only session

### ISSUE THREAD

**Issue by bgraf-zlab** [graphcool/graphcool-cli#88]
When there's no graphical browser available (i.e. on a remote server when logged in via ssh), the graphcool-cli hangs on authentication ("`You need to authenticate. Your browser will open shortly...`").

It would be nice if there was a fallback for authentication on the CLI, if possible. (Maybe even by generating a token or key in the graph.cool web console/backend and copying that over to the terminal.)

(I helped myself by authenticating on my local machine and copying `~/.graphcoolrc` to the remote machine, but well...)

**Comment by JPinlac** [comment]
Trying to follow the quickstart-with-apollo with angular, the step *graphcool init --schema http://graphqlbin.com/instagram.graphql* errors out during authentication. 
```
  graphcool Error: Whoops, something went wrong during authentication.
  graphcool
  graphcool     at Object.<anonymous> (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:26:19)
  graphcool     at throw (native)
  graphcool     at rejected (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:5:65)
  graphcool     at process._tickDomainCallback (internal/process/next_tick.js:129:7) +0ms
```

**Comment by schickling** [comment]
Thanks a lot for bringing this up @bgraf-zlab. The CLI already supports a token-based auth flow, we just need to add the corresponding feature to the Console. I've opened a feature issue here: https://github.com/graphcool/console/issues/1116
