### ISSUE TITLE
Consider using plugin based architecture for cli

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool-cli#98]
I really like the way heroku-cli is using a plugin architecture for all of the functionality the cli offers, and for their ability to enable user plugin development. https://github.com/heroku/cli Since we were discussing using a plugin model to support multiple data formats for the upcoming import feature, I thought I'd share this. It offers a starting point for a more modular approach, as I expect something like this will be necessary when the cli starts to grow, and the community will get more involved with it.

**Comment by schickling** [comment]
I really like this idea and we should definitely keep it in mind as the CLI evolves! Probably a good fit for v2 of the CLI.

**Comment by timsuchanek** [comment]
Done in 1.3.13 beta :)
